"""New Database

Revision ID: b8fb65afd3dc
Revises: 
Create Date: 2024-09-05 14:26:39.386591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fb65afd3dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='unique_email_constraint'),
    sa.UniqueConstraint('username', name='unique_username_constraint')
    )
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_user_username'), ['username'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('asset_content', sa.Text(), nullable=False),
    sa.Column('asset', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_type'), ['type'], unique=False)

    op.create_table('benefit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('comparison', sa.Text(), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benefit_type'), ['type'], unique=False)

    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type'), ['type'], unique=False)

    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_duration', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ideal_audience', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_subscription_duration'), ['subscription_duration'], unique=False)

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_title'), ['title'], unique=False)

    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_title'), ['title'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='unique_email_constraint'),
    sa.UniqueConstraint('username', name='unique_username_constraint')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benefits_title'), ['title'], unique=False)

    op.create_table('option_feature',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.PrimaryKeyConstraint('option_id', 'feature_id')
    )
    op.create_table('page_section',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'section_id')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_title'), ['title'], unique=False)

    op.create_table('section_asset',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'asset_id')
    )
    op.create_table('section_content',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'content_id')
    )
    op.create_table('benefit_listing',
    sa.Column('benefits_id', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], ),
    sa.ForeignKeyConstraint(['benefits_id'], ['benefits.id'], ),
    sa.PrimaryKeyConstraint('benefits_id', 'benefit_id')
    )
    op.create_table('pricing_option',
    sa.Column('pricing_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['pricing_id'], ['pricing.id'], ),
    sa.PrimaryKeyConstraint('pricing_id', 'option_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_option')
    op.drop_table('benefit_listing')
    op.drop_table('section_content')
    op.drop_table('section_asset')
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_title'))

    op.drop_table('pricing')
    op.drop_table('page_section')
    op.drop_table('option_feature')
    with op.batch_alter_table('benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benefits_title'))

    op.drop_table('benefits')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_title'))
        batch_op.drop_index(batch_op.f('ix_section_name'))

    op.drop_table('section')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_title'))
        batch_op.drop_index(batch_op.f('ix_page_slug'))

    op.drop_table('page')
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_subscription_duration'))
        batch_op.drop_index(batch_op.f('ix_option_action'))

    op.drop_table('option')
    op.drop_table('feature')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_title'))

    op.drop_table('content')
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benefit_type'))

    op.drop_table('benefit')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_type'))
        batch_op.drop_index(batch_op.f('ix_asset_title'))
        batch_op.drop_index(batch_op.f('ix_asset_asset'))

    op.drop_table('asset')
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_user_username'))
        batch_op.drop_index(batch_op.f('ix_admin_user_email'))

    op.drop_table('admin_user')
    # ### end Alembic commands ###
