"""Pricing Option class

Revision ID: d9d65d94120e
Revises: b8fb65afd3dc
Create Date: 2024-09-05 14:40:11.264787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d65d94120e'
down_revision = 'b8fb65afd3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.Text(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
