"""Options saving

Revision ID: dec2d0d25873
Revises: d9d65d94120e
Create Date: 2024-09-05 16:58:08.501291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec2d0d25873'
down_revision = 'd9d65d94120e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saving', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_column('saving')

    # ### end Alembic commands ###
