"""web content models restructure

Revision ID: fa7d8fe2175e
Revises: 2bf6efaea5b0
Create Date: 2024-08-28 16:43:11.809529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7d8fe2175e'
down_revision = '2bf6efaea5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('asset', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_type'), ['type'], unique=False)

    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_title'), ['title'], unique=False)

    op.create_table('page_section',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'section_id')
    )
    op.create_table('section_asset',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'asset_id')
    )
    op.create_table('section_content',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'content_id')
    )
    op.drop_table('page_content')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index('ix_content_section')
        batch_op.create_index(batch_op.f('ix_content_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type'), ['type'], unique=False)
        batch_op.drop_column('section')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.drop_index('ix_page_name')
        batch_op.create_index(batch_op.f('ix_page_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_title'), ['title'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_page_title'))
        batch_op.drop_index(batch_op.f('ix_page_slug'))
        batch_op.create_index('ix_page_name', ['name'], unique=False)
        batch_op.drop_column('slug')
        batch_op.drop_column('title')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_title'))
        batch_op.create_index('ix_content_section', ['section'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('type')
        batch_op.drop_column('title')

    op.create_table('page_content',
    sa.Column('page_id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'content_id')
    )
    op.drop_table('section_content')
    op.drop_table('section_asset')
    op.drop_table('page_section')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_title'))

    op.drop_table('section')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_type'))
        batch_op.drop_index(batch_op.f('ix_asset_title'))
        batch_op.drop_index(batch_op.f('ix_asset_asset'))

    op.drop_table('asset')
    # ### end Alembic commands ###
